[19기 안정현]add:메인페이지 Nav바 카테고리 리스트 구현
wecode-bootcamp-korea/19-2nd-CareOfLegend-backend pull request #2
Opened 2021-04-29 11:28 UTC by ahnjeonghyun

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카테고리 리스트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 메인페이지 Nav바 카테고리 리스트 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-04-30 01:27 UTC, jamessoun93 commented
유닛테스트 추가해주세요!

2021-04-30 01:35 UTC, jamessoun93 requested changes

2021-04-30 01:35 UTC, jamessoun93 commented on products/views.py
> +        categories    = MainCategory.objects.all()
`=` 앞에 불필요하게 많은 공백을 주셨는데 없애주세요.

2021-04-30 01:35 UTC, jamessoun93 commented on products/views.py
> +        result=[{
`=` 앞뒤로 한칸씩 추가해주세요.

2021-04-30 01:35 UTC, jamessoun93 commented on products/views.py
> +                'subcategory_name':[{
가독성을 위해 `:` 기준으로 정렬해주시고, `subcategory_name` 변수명 재확인해주세요. 해당 key 값에 담기는 value 의 자료형이 무엇인지 확인 후 더 알맞은 변수명으로 변경해주세요.

2021-04-30 01:35 UTC, jamessoun93 commented on products/views.py
> +                           'subcategory_name':subcategory.name} for subcategory in category.subcategory_set.all() ] }
여기도 formatting 신경써주세요.

2021-04-30 07:33 UTC, ahnjeonghyun commented on products/views.py
> +        categories    = MainCategory.objects.all()
네 수정하겠습니다.

2021-04-30 07:33 UTC, ahnjeonghyun commented on products/views.py
> +        result=[{
넵 수정하겠습니다

2021-04-30 07:33 UTC, ahnjeonghyun commented on products/views.py
> +                'subcategory_name':[{
네 복수형으로 변경했습니다.

2021-04-30 07:33 UTC, ahnjeonghyun commented on products/views.py
> +                           'subcategory_name':subcategory.name} for subcategory in category.subcategory_set.all() ] }
넵 수정하겠습니다~

2021-04-30 12:08 UTC, ahnjeonghyun commented
![스크린샷 2021-04-30 오후 9 00 10](https://user-images.githubusercontent.com/74334412/116692954-24d73800-a9f8-11eb-9618-e24f8c53b127.png)
이렇게 하는거 맞나요 ㅠ

2021-05-01 05:19 UTC, Kang-kyunghun requested changes

2021-05-01 05:19 UTC, Kang-kyunghun commented on products/views.py
> +from products.models            import MainCategory, SubCategory
```suggestion
from django.http     import JsonResponse
from django.views    import View

from products.models import MainCategory, SubCategory
```
```suggestion
from django.http                import JsonResponse
from django.views               import View

from products.models            import MainCategory, SubCategory
```
가장 긴 것을 기준으로 한 칸정도만 띄어주면 됩니다~

2021-05-01 05:19 UTC, Kang-kyunghun commented on products/views.py
> +        result=[{
이 부분 아직 수정이 안 되었네요~

2021-05-01 05:19 UTC, Kang-kyunghun commented on products/views.py
> +                'subcategories' : [
: 을 기준으로 정렬해 주세요.

2021-05-01 05:34 UTC, ahnjeonghyun commented on products/views.py
> +        result=[{
아 result인줄 몰랐네요 ㅎㅎ 수정했습니다.

2021-05-01 05:34 UTC, ahnjeonghyun commented on products/views.py
> +from products.models            import MainCategory, SubCategory
넵 수정하겠습니다!

2021-05-01 05:35 UTC, ahnjeonghyun commented on products/views.py
> +                'subcategories' : [
넵 수정하겠습니다~

2021-05-03 01:19 UTC, jamessoun93 requested changes

2021-05-03 01:19 UTC, jamessoun93 commented on products/tests.py
> +    def test_categoriy_get_sucess(self):
오타 확인해주세요.

2021-05-03 01:19 UTC, jamessoun93 commented on products/views.py
> +                for category in categories ]
여기 indent 가 전부 8칸인데 4칸으로 전부 통일해주세요.

2021-05-03 05:11 UTC, ahnjeonghyun commented on products/views.py
> +                for category in categories ]
넵 수정했습니다

2021-05-03 05:11 UTC, ahnjeonghyun commented on products/tests.py
> +    def test_categoriy_get_sucess(self):
category 오타 수정했습니다.

2021-05-03 07:34 UTC, jamessoun93 commented
LGTM

2021-05-03 07:34 UTC, merged