[19기 박형섭] Add: 상품 카테고리 뷰 작성
wecode-bootcamp-korea/19-2nd-CareOfLegend-backend pull request #3
Opened 2021-04-29 11:47 UTC by Panamax-Bryan

## 수정 사항 간략한 한줄 요약
- SubCategory 목록을 불러오는 class 작성
- HealthGoal 목록을 불러오는 class 작성
- products에 관한 urls 작성
- products의 class에 관한 urls 작성

		 
## 수정 사항들 자세한 내용
- SubCategory 목록을 불러오기
![image](https://user-images.githubusercontent.com/62834684/116545961-073c9c80-a92c-11eb-996c-3f1e19454995.png)

- HealthCategory 목록을 불러오기
![image](https://user-images.githubusercontent.com/62834684/116545774-cb093c00-a92b-11eb-89f8-b2aa5f703256.png)

## 기타 질문 및 특이 사항
- 유닛 테스트는 세션 강의를 한번 더 들어보고 작성할 예정이어서, 이번 PR에 포함되지 않았습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-04-30 01:31 UTC, jamessoun93 requested changes

2021-04-30 01:31 UTC, jamessoun93 commented on products/views.py
> +        maincategories = MainCategory.objects.all()
변수명에서 두개의 단어 조합은 `_`로 구분해주세요!

2021-04-30 01:31 UTC, jamessoun93 commented on products/views.py
> +                'sub_category' : [{
value가 list 인 경우 key 를 복수형으로 지어주세요.

2021-04-30 01:31 UTC, jamessoun93 commented on products/views.py
> +        healthgoals = HealthGoal.objects.all()
여기도 변수명 확인해주세요!

2021-04-30 01:32 UTC, jamessoun93 requested changes

2021-04-30 01:32 UTC, jamessoun93 commented on products/urls.py
> +        path('/healthgoal', HealthGoalView.as_view())
해당 path 는 RESTful 규칙에 맞지 않습니다. 어떻게 변경해야 RESTful 할까요?

2021-04-30 03:48 UTC, Panamax-Bryan commented on products/views.py
> +        maincategories = MainCategory.objects.all()
네, 모든 변수명을 수정했습니다.

2021-04-30 03:51 UTC, Panamax-Bryan commented on products/views.py
> +                'sub_category' : [{
네, 복수형으로 수정했습니다.

2021-04-30 03:53 UTC, Panamax-Bryan commented on products/views.py
> +        healthgoals = HealthGoal.objects.all()
네, 변수명을 수정했습니다.

2021-04-30 10:58 UTC, Panamax-Bryan commented on products/urls.py
> +        path('/healthgoal', HealthGoalView.as_view())
네, RESTful 규칙에 맞게 수정했습니다.

2021-05-03 01:25 UTC, jamessoun93 requested changes

2021-05-03 01:25 UTC, jamessoun93 commented on products/urls.py
> +        path('/product-category', ProductCategoryView.as_view()),
이미 products app 으로 라우팅 될때부터 `products` 라는 path 를 달고 들어올텐데 굳이 `products/product-category` 이렇게 중복으로 product 를 넣어주실 필요가 없습니다. 수정해주세요!

2021-05-03 01:25 UTC, jamessoun93 commented on products/views.py
> +            } for category in categories]
👍👍👍

2021-05-03 02:28 UTC, Panamax-Bryan commented on products/urls.py
> +        path('/product-category', ProductCategoryView.as_view()),
네, 수정했습니다.

정현님이 상품 리스트를 구현하면서 'categories'를 사용해서, 저는 'subcategories'로 수정했습니다.

2021-05-03 02:55 UTC, redsaumon commented on products/tests.py
> +
어디에 사용되는 변수인가요? 사용하지 않는다면 지워주세요!

2021-05-03 02:55 UTC, redsaumon commented on products/tests.py
> +
ProductCategoryView의 url은 subcategories로 수정하신 거 같은데 확인 부탁드려요!

2021-05-03 04:01 UTC, Panamax-Bryan commented on products/tests.py
> +
네, 삭제했습니다!

해당 변수는 테스트 파일을 만드는 과정에서 오류를 해결하기 위해서 추가한 변수였습니다.

2021-05-03 04:51 UTC, Panamax-Bryan commented on products/tests.py
> +
네, 수정했습니다!

2021-05-04 01:20 UTC, jamessoun93 commented
conflict 해결해주세요!

2021-05-04 07:16 UTC, Panamax-Bryan commented
> conflict 해결해주세요!

네, 해결했습니다!

2021-05-06 01:31 UTC, jamessoun93 commented
LGTM

2021-05-06 01:31 UTC, merged