[CareOfLegend 19기 김현영]Add:kakao 소셜 로그인 엔드포인트 구현
wecode-bootcamp-korea/19-2nd-CareOfLegend-backend pull request #4
Opened 2021-04-30 03:13 UTC by hyun0k

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- kakao 소셜 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 엔드포인트 구현 및 view추가에 따른 url 추가
- 로그인 데코레이터 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 아직 unit test 코드는 작성하지 않았습니다. 공부해서 주말안에 완료하도록 하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-04-30 15:09 UTC, Kang-kyunghun requested changes

2021-04-30 15:09 UTC, Kang-kyunghun commented on users/views.py
> +            user         = User.objects.get(user_code=data['id'])
get으로 DB에 있는 카카오 유저의 고유 번호를 비교해서 로그인을 시도하고 있는데, 그러면 최초의 카카오 유저의 고유 번호는 언제 저장하나요?

2021-04-30 15:09 UTC, Kang-kyunghun commented
혹시 소셜 로그인 유닛테스트는 우선 순위를 뒤로 하라고 가이드 받으셨나요?

2021-05-01 04:42 UTC, hyun0k commented on users/views.py
> +            user         = User.objects.get(user_code=data['id'])
카카오의 유저 고유번호를 저장하는 View를 따로 만들 계획입니다. 최초에 카카오 로그인 했을때는 프로필 이미지과 닉네임을 등록하도록 팝업을 띄워서 그 때 카카오 유저 고유번호와 입력정보를 DB에 저장되는 프로세스로 기획을 했습니다. 그런데, 이와 같은 프로세스일때 따로 View를 짜는 것이 맞는 방법인지 궁금합니다.

2021-05-01 04:42 UTC, hyun0k commented
> 혹시 소셜 로그인 유닛테스트는 우선 순위를 뒤로 하라고 가이드 받으셨나요?

다른 View를 먼저 작성하라는 말씀이신가요?

2021-05-01 05:22 UTC, Kang-kyunghun requested changes

2021-05-01 05:22 UTC, Kang-kyunghun commented on users/views.py
> +            user         = User.objects.get(user_code=data['id'])
그러면 어쨌든 카카오로 로그인 하는 view가 2개가 되어 중복되는 느낌이 있습니다. djagno ORM 중에 get_or_create method가 있습니다. 한 번 알아보고 적용하면 좋을 것 같습니다.

2021-05-01 05:22 UTC, Kang-kyunghun commented
아니요. 소셜 로그인 유닛테스트가 없는 것 같아서 물어 봤습니다.

2021-05-01 05:23 UTC, Kang-kyunghun commented
> > 혹시 소셜 로그인 유닛테스트는 우선 순위를 뒤로 하라고 가이드 받으셨나요?
> 
> 다른 View를 먼저 작성하라는 말씀이신가요?
>
> 아니요. 소셜 로그인 유닛테스트가 없어서 물어 봤습니다.

2021-05-01 05:24 UTC, hyun0k commented on users/views.py
> +            user         = User.objects.get(user_code=data['id'])
넵 알아보고 적용시켜보겠습니다!

2021-05-01 05:26 UTC, hyun0k commented
> > > 혹시 소셜 로그인 유닛테스트는 우선 순위를 뒤로 하라고 가이드 받으셨나요?
> > 
> > 
> > 다른 View를 먼저 작성하라는 말씀이신가요?
> > 아니요. 소셜 로그인 유닛테스트가 없어서 물어 봤습니다.

수정사항 반영하고 unit test까지 작성해서 다시 리뷰요청 드리겠습니다.

2021-05-04 01:40 UTC, jamessoun93 approved these changes

2021-05-04 01:41 UTC, merged