[19기 안정현]Add:상품리스트 기능구현
wecode-bootcamp-korea/19-2nd-CareOfLegend-backend pull request #9
Opened 2021-05-05 11:40 UTC by ahnjeonghyun

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품리스트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 전체상품 , 서브카테고리 상품 리스트 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-05 17:43 UTC, ahnjeonghyun commented
<img width="651" alt="스크린샷 2021-05-06 오전 2 42 31" src="https://user-images.githubusercontent.com/74334412/117185419-c7d2ec00-ae14-11eb-8448-dd04ed8f1114.png">
<img width="653" alt="스크린샷 2021-05-06 오전 2 41 48" src="https://user-images.githubusercontent.com/74334412/117185428-cb667300-ae14-11eb-9871-35f320b37664.png">
<img width="646" alt="스크린샷 2021-05-06 오전 2 41 28" src="https://user-images.githubusercontent.com/74334412/117185430-cbff0980-ae14-11eb-8132-24976d109e54.png">

2021-05-06 01:45 UTC, jamessoun93 requested changes

2021-05-06 01:45 UTC, jamessoun93 commented on products/views.py
> +                products = Product.objects.filter(is_new = is_new)
만약 sub_categories 와 is_new 가 둘다 들어왔을때는 sub_categories 로 필터를 한 뒤 그 결과물에 is_new 로 또 필터 쿼리를 날려야하는데, 조건에 맞는 filter 조건들을 먼저 만들고 쿼리는 한번만 날릴 수 있는 방법이 있습니다.

아래 예시를 참고하여 한번 적용해보세요!
```python
# Filter using Q object

q = Q()

if types:
    q &= Q(types__name__in = types)
if max_num_ppl:
    q &= Q(maximum_number_of_people__lte = max_num_ppl)

rooms = Room.objects.filter(q)
```

2021-05-06 02:31 UTC, ahnjeonghyun commented on products/views.py
> +                products = Product.objects.filter(is_new = is_new)
넵 찾아보고 적용해보겠습니다.

2021-05-06 06:43 UTC, ahnjeonghyun commented
![Uploading 스크린샷 2021-05-06 오후 3.40.36.png…]()

2021-05-06 07:42 UTC, jamessoun93 approved these changes
LGTM 👍

2021-05-06 07:43 UTC, merged